### ISSUE TITLE
Self-assignment in RequestParams.java + fields should be private

### ISSUE THREAD

**Issue by 7332f2b2bc38da967b2b** [epam/JDI#118]
Due to a typo, it seems that the **headers** variable is assigned to itself in the RequestParams() constructor.
```java   
public RequestParams(Headers urlParams) {
        this.headers = headers;
}
```
It should probably be:

```java   
public RequestParams(Headers headers) {
        this.headers = headers;
}
```

Also, all the fields in the **[RequestParams](https://github.com/epam/JDI/blob/master/Java/JDI/jdi-http/src/main/java/com/epam/http/requests/RequestParams.java)** class are currently public. They should probably be set to private.

**Comment by Supreme85** [comment]
thanks, I fix that
