### ISSUE TITLE
C#, do not work frames functionality.

### ISSUE THREAD

**Issue by makclv** [epam/JDI#15]
Examle:

The page: http://www.w3schools.com/html/html_iframe.asp
The frame on this page: http://www.w3schools.com/html/default.asp

I'm trying to click the menu item 'Bootstrap' inside the frame, but the library click the menu item 'Bootstrap' from the original page.

Sample code:

`

    [Test]
    public void FramesTest()
    {
        W3CSite.W3CPageWithFrame.Open();
        W3CSite.W3CPageWithFrame.Frame.BootstrapMenuItem.Click();
    }
        
    [Site(Domain = "http://www.w3schools.com/", DemoMode = false)]
    public class W3CSite : WebSite
    {
        [Page(Url = "http://www.w3schools.com/html/html_iframe.asp")]
        public static W3CPageWithFrame W3CPageWithFrame;
    }
    
    public class W3CPageWithFrame : WebPage
    {
        [Frame(ByXPath = "//iframe[@src='default.asp']")]
        public ExampleFrame Frame;
    }
    
    public class ExampleFrame : Section
    {
        [FindsBy(How = How.LinkText, Using = "BOOTSTRAP")]
        public Link BootstrapMenuItem;
    }
`

![c414b-clip-202kb](https://cloud.githubusercontent.com/assets/20574052/17021190/f2268496-4f4e-11e6-8047-03e0bcaa82ba.png)

**Comment by Supreme85** [comment]
Fixed in JDI.UIWeb 1.0.17
