### ISSUE TITLE
There is no ability to parse HTML body in the JDI HTTP library - Alex Lyubenkov

### ISSUE THREAD

**Issue by savvagen** [epam/JDI#160]
Software: JDI Http

Description: Is there is no ability "Out Of the box " to parse the HTML body. xml-path - exist, jsonpath - exist, but there is no way to path Html in the "response.body()" method

Actual:
User need to download other helper libraries like JSoup 

Expected:
It will be helpful to parse the HTML response body with additional methods like:
Example:
findElement()
parseHtmlBody() in the body() method

**Comment by Supreme85** [comment]
fixed in version 1.0.90
