### ISSUE TITLE
Locator inside an element of list finds all elements on a page if 'useCache' is disabled

### ISSUE THREAD

**Issue by Aks1389** [epam/JDI#173]
For example I have a Elements< PageObjectClass > list;
There is some element in the PageObjectClass.
If set useCache property as false, then at attempt to get element inside PageObjectClass an exception occurs with message that there were found N elements instead of one. When default value of 'useCache' is stayed there is no exception occured.

```
@FindBy(xpath ="some_locator")
private Elements<PageObjectClass> list;

public void getListItemName(String name){
  list.useCache=false;
   for(PageObjectClass listItem : list){
         logger.info(listItem.getItemName());
   }
}


public class PageObjectClass extends Section{
@FindBy(xpath = "some_locator")   <-- this locator finds several elements instead of one
private Text text;

public String getItemName(){
   return text.getText();
}
}
```

**Comment by Supreme85** [comment]
fixed in 1.0.85
