### ISSUE TITLE
[JDI UI] ExceptionInInitializerError in Layout class for "headless" environment

### ISSUE THREAD

**Issue by Savostytskyi** [epam/JDI#182]
When I try to execute some UI tests in headless environment (without monitor) using Jenkins for example I will receive exception:
`<Stopped 0 worker daemon(s).
    [error] Can't initialize global Robot for Mouse: headless environment
    [error] ***** Terminating SikuliX after a fatal error 999 *****
    It makes no sense to continue!
    If you do not have any idea about the error cause or solution, run again
    with a Debug level of 3. You might paste the output to the Q&A board.

com.epam.qa.runners.FrontendTestRunner.setUp FAILED
    java.lang.ExceptionInInitializerError
        at com.epam.jdi.uitests.core.settings.Layout.<clinit>(Layout.java:61)>`

It coused by initialization of **org.sikuli.script.Screen** in **com.epam.jdi.uitests.core.settings.Layout** without any needed of it's initialization because I doesn't use sikuli at all. So the posible fix for this case is: Initialize screen variable only if required:

```
public class Layout {

    ...........

    private static Screen screen = null;

    ...........

    private static Screen getScreen() {
        if(screen == null)
            screen = new Screen();
        return screen;
    }
}
```

This simple issue stop me in using JDI-UI framework.

**Comment by Supreme85** [comment]
you can switch off sikulli using test.properties
verifyLayout=false
(and as i know it switched off by default) or even in this case you got this error?

**Comment by Savostytskyi** [comment]
Hello Roman,
Yes I have, bacause during call verifyLayout variable in if statement, 
private static Screen screen=new Screen() initializing 
and during initializing I have exception. So my solution is just simply init this class field only is needed. Because now even if verifyLayout=false we will still call sikuli Screen class.

**Comment by Supreme85** [comment]
Fixed
Move all Screen initializations in getScreen() method
    public static Screen getScreen() {
        if (shouldVerifyLayout && screen == null)
            screen = new Screen();
        return screen;
    }
new Screen will be called only if shouldVerifyLayout = true (equal to test.property verifyLayout=true)
https://github.com/epam/JDI/blob/master/Java/JDI/jdi-uitest-core/src/main/java/com/epam/jdi/uitests/core/settings/Layout.java
