### ISSUE TITLE
[Java][Settings] Since version 1.0.90 driver is not started with custom path

### ISSUE THREAD

**Issue by Aks1389** [epam/JDI#185]
No able to run test when driver has custom path. There is message in the console that jdi tries to find it in the default directory, despite the custom path was specified.

`Drivers: CHROME:com.epam.jdi.uitests.web.selenium.driver.SeleniumDriverFactory$$Lambda$21/1258801872@355bffcf; Run: java.lang.ThreadLocal@3b5d1662Exception: The driver executable does not exist: ...\src\main\resources\driver\chromedriver.exe`

**Comment by Supreme85** [comment]
fixed in 1.1.2
