### ISSUE TITLE
Windows style paths cause OSX to break

### ISSUE THREAD

**Issue by zyme** [epam/JDI#186]
Do action Open page 'TestAppSite' failed. Can't get result. Reason: java.lang.AssertionError: Can't get driver; Thread: 1
Drivers: FIREFOX:com.epam.jdi.uitests.web.selenium.driver.SeleniumDriverFactory$$Lambda$7/1816757085@ca263c2; Run: java.lang.ThreadLocal@52e677afException: The driver executable does not exist: /sandbox/data-donation-platform/ddp/ddp-automation\src\main\resources\driver\\geckodriver

**Comment by Supreme85** [comment]
Fixed in version 1.1.2
