### ISSUE TITLE
Detailed instructions for Java sample tests

### ISSUE THREAD

**Issue by alexeykuptsov** [epam/JDI#19]
We need step-by-step instructions to run sample tests. For me (as a developer who deals with Java not very often) it it was slightly harder to run them than:

> just download this simplest Java example and run test

It turned up not so obvious to run Maven, and I had to google its syntax.

**Comment by Supreme85** [comment]
1. Ckick Link
2. Unpack zip
3. Double click on pom.xml (if it is not setup to open with Idea by default setuo this)
4. Find test class in tree on left
5. Right click on test class (SmokeTest.cs) or in test method
6. Choose Run 'SmokeTest' // Run '<chosen test>'

**Comment by alexeykuptsov** [comment]
I didn't expect that the issue would be closed so quickly. It wasn't a StackOverflow like question. I believe that lack of such details in documentation is a project issue. :-)
Please check the possible solution in my fork:
https://github.com/alexeykuptsov/JDI/tree/feature/readme-sample-project
I've added `test.properties` with `driver.getLatest=true` file to the sample project (forked it too). Because this makes it easier to start. And this approach is platform independendent (since `chromedriver.exe` doesn't make sence at Linux).
