### ISSUE TITLE
Update webdrivermanager to 2.1.0

### ISSUE THREAD

**Issue by sskovalevskiy** [epam/JDI#195]
Webdrivermanager dependency (https://github.com/bonigarcia/webdrivermanager) used in JDI has 1.7.2 version, and it clashes with selenide's webdrivermanager dependency. Latest version of Selenide (4.10.01) uses webdrivermanager-2.1.0 which doesn't contain class io.github.bonigarcia.wdm.BrowserManager. If our project already uses Selenide, and we add JDI -> we catch NoSuchMethodError.

**Comment by Supreme85** [comment]
Change version of download manager to RELEASE (now 2.1.0)
Will appear in version 1.1.10
