### ISSUE TITLE
getFromList method isn't working for hidden webelements

### ISSUE THREAD

**Issue by lyubenkov** [epam/JDI#202]
JDI getFromList(List<WebElement> els, String name) method in class BaseSelector.java isn't working for hidden webelements, due to the Selenium design choice: "getText returns empty string for invisible elements. It is a desing choise. Full stop."  (source https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/6415).
So when elements are hidden, JDI falls with error:
`throw exception("Can't find option '%s'. Please fix allLabelsLocator", name);`

I think the textContent attribute is a better option.

**Comment by RomanIovlev** [comment]
Fixed in 1.1.14

**Comment by lyubenkov** [comment]
The fix isn't working, you're catching Exception, but it throws AssertionError in the end.

**Comment by lyubenkov** [comment]
1.1.15 fixed the problem
