### ISSUE TITLE
Unable to send propertyFile path for different environments

### ISSUE THREAD

**Issue by bsdang** [epam/JDI#214]
Unable to send propertyFile path different environments, com.epam.jdi.uitests.web.settings.WebSettings assumes filename to be test.properties and uses that only, this forbids us from using different property files for different environments

**Comment by RomanIovlev** [comment]
you can change file to your property path using
JDIPropertiesReader.getProperties("other.properties")
or 
JDIPropertiesReader.getProperties("env/other.properties") if properies placed in not root folder of test/resources
