### ISSUE TITLE
Custom driver initialization

### ISSUE THREAD

**Issue by kshirunov** [epam/JDI#35]
Please, do not use enum DriverTypes. It would be better to have an interface for WebDriver loading, some classes responsible for common WebDriver launching (FF, Chrome, IE) and some kind of method to add user classes implementing the interface. 
There are requests for Linux Chrome support, custom grid. Also I couldn't use you FF implementation because of a browser plugin required on my service. All that extensions could be implemented by users without library changing.

**Comment by iCok** [comment]
What's problem to use this one?

public static String useDriver(Supplier<WebDriver> driver) {
        return getDriverFactory().registerDriver(driver);
    }

**Comment by kshirunov** [comment]
OK, but how to find that method without javadoc, documentation and samples?

Also lets review your TestNGBase class sample and @BeforeSuite and @AfterSuite sections.
Are you sure that killAllRunWebDrivers() method should be applied on Linux? And should it kills my IE during FF or remote testing? So, interface for browser load and shutdown is necessary.
