### ISSUE TITLE
PropertyReader.readProperties() method never throws IOException 

### ISSUE THREAD

**Issue by vovik815** [epam/JDI#37]
com.epam.commons.PropertyReader:
the method catches all the exceptions and doesn't throw  IOException 

here is the method definition
private static Properties readProperties() throws IOException {
        properties = new Properties();
        try {
            inputStream = PropertyReader.class.getResourceAsStream(getCorrectPath());
            if (inputStream != null)
                properties.load(inputStream);
        } catch (Exception ex) {
            if (inputStream != null) inputStream.close();
        }
        return properties;
    }

**Comment by Supreme85** [comment]
inputStream.close() throws this exception unforunately
