### ISSUE TITLE
Java-version build fails on Travis CI

### ISSUE THREAD

**Issue by elv1s42** [epam/JDI#5]
Full log is [here](https://travis-ci.org/epam/JDI).

> [INFO] Compiling 83 source files to /home/travis/build/epam/JDI/Java/JDI/jdi-uitest-web/target/classes
> An exception has occurred in the compiler (1.8.0_31). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
> java.lang.NullPointerException
>     at com.sun.tools.javac.code.Types.isConvertible(Types.java:290)
>     at com.sun.tools.javac.comp.Check.assertConvertible(Check.java:922)
>     at com.sun.tools.javac.comp.Check.checkMethod(Check.java:876)

Overall build information:

> [INFO] EPAM UI Test Framework ................................ SUCCESS [  4.403 s]
> [INFO] jdi-commons .................................................... SUCCESS [  6.296 s]
> [INFO] EPAM JDI UI Testing Framework Core ............ SUCCESS [  1.179 s]
> [INFO] jdi-matchers ..................................................... SUCCESS [  4.566 s]
> [INFO] EPAM JDI UI Testing Web ................................ FAILURE [  9.233 s]
> [INFO] jdi-uitest-mobile ................................................ SKIPPED
> [INFO] jdi-uitest-gui ...................................................... SKIPPED
> [INFO] EPAM JDI UI Testing Unit tests ......................... SKIPPED
> [INFO] EPAM JDI UI Testing Tutorial Tests .................. SKIPPED
> [INFO] EPAM JDI UI Testing Unit tests ......................... SKIPPED
> [INFO] jdi-uitest-mobiletests ......................................... SKIPPED
> [INFO] jdi-uitest-guitests ............................................... SKIPPED
> [INFO] EPAM JDI UI Testing Unit tests ......................... SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE

**Comment by iCok** [comment]
In local type it compiles successfully, so probably you need to change jdk and try again. But also I fixed little issue in parent pom.

**Comment by elv1s42** [comment]
Fixed in https://github.com/epam/JDI/pull/48/
Thanks @mefateah

**Comment by mefateah** [comment]
you are welcome
