### ISSUE TITLE
[Feature] Implement Xml log format

### ISSUE THREAD

**Issue by Supreme85** [epam/JDI#58]
It will be good to have logs in xml format so user can easily collapse and expand details for each step

e.g. 

> <info>Fill login form
> <info>Input 'admin' in login field
> <info>Find element by css '.login'</info>
> </info>
> <info>Input 'P@ssword' in password field
> <info>Find element by css '.psw'</info>
> </info>
> </info>

code for this should look like:
```
public static void main()
{ log.info("Fill login form", () -> fillForm()); }
public static void fillForm()
{ fillField("login", "login"); fillField("password", "P@ssword"); }
public static void fillField(String field, String value)
{ log.info(format("Input '%s' in login field", value), () -> find(field)); }
public static void find(String field)
{ log.info(format("Find element by css '%s'", value == login ? ".login" : ".psw")); }
```

**Comment by alexeykuptsov** [comment]
What app is supposed to be used for XML logs reading? Just interested in the tool with collapse/expand feature.

**Comment by Supreme85** [comment]
For example you can use notepad++ or any other pro text readers

**Comment by alexeykuptsov** [comment]
Cool. Never thought about Notepad++ as an XML viewer. Thanks. 
It also might be interesting to use TeamCity blocks of service messages to support the collapse/expand feature directly in TeamCity Build Log report: https://confluence.jetbrains.com/plugins/servlet/mobile#BuildScriptInteractionwithTeamCity-BlocksofServiceMessages
