### ISSUE TITLE
Improve logging of page objects initialization failures

### ISSUE THREAD

**Issue by wsbaser** [epam/JDI#6]
AR:
If some field in page object is initialized incorrectly, framework throws an exception:
java.lang.AssertionError: Error in getElementInstance for field 'table' with type 'CustomTable
customelements.CustomTable'

ER:
Sometimes it is hard to find incorrect field in page object having only field name and field type.
Page object class/component class should be also logged.

**Comment by Supreme85** [comment]
will be fixed in 1.0.18
