### ISSUE TITLE
Support for models with inheritance in form.fill()

### ISSUE THREAD

**Issue by wsbaser** [epam/JDI#7]
class ModelBase{
   String fieldA; 
} 
class MyModel extends ModelBase{
   String fieldB; 
}
MyModel model = new MyModel();
model.fieldA = "A";
model.fieldB = "B";
form.fill(model);

AR:
Only fieldB is set in web interface.

ER:
Both fieldA and fieldB are set in web interface.

NOTE:
ReflectionUtils.getFields does not return fields from inheritance chain. That is the reason of the problem.

**Comment by Supreme85** [comment]
Fixed in 1.0.9
