### ISSUE TITLE
Fix all tests on Java - Alex Shiganov

### ISSUE THREAD

**Issue by Supreme85** [epam/JDI#79]
Go through all tests in Java run them and be sure that all tests passed on 1.0.70 version
Fix issues if found

https://github.com/epam/JDI/tree/master/Java/Tests
jdi-uitest-tutorialtests
jdi-uitest-web-examples
jdi-uitest-webtests

Start 07.06

**Comment by dancingolav** [comment]
jdi-uitest-tutorialtests - fixed
jdi-uitest-web-examples -fixed
jdi-uitest-webtests -fixed
