### ISSUE TITLE
Do not throw away parent search context

### ISSUE THREAD

**Issue by wsbaser** [epam/JDI#8]
componentA.parent = null;
componentA.avatar.byLocator = someLocator;
componentA.someButton.click();

AR:
someButton.searchContext == null

ER:
someButton.searchContext == componentA.avatar.byLocator

NOTES:
searchContext is not null ONLY IF all parents are not null

The problem is here:
        if(element != null && ReflectionUtils.isClass(element.getClass(), BaseElement.class) && ((p = (el = (BaseElement)element).getParent()) != null || el.avatar.frameLocator != null)) {

**Comment by Supreme85** [comment]
Fixed in 1.0.9
