### ISSUE TITLE
[Feature] Add verify layout functionality

### ISSUE THREAD

**Issue by Supreme85** [epam/JDI#92]
It is possible to compare current layout of application vs image using Sikuli
Add method to [WebPage](https://github.com/epam/JDI/blob/master/Java/JDI/jdi-uitest-web/src/main/java/com/epam/jdi/uitests/web/selenium/elements/composite/WebPage.java) which compares current scrren with specified image file like

homePage.verifyLayout("image/homepage.jpeg")

**Comment by DonyaCool** [comment]
Hi, could you please assign this task to me? Dmitriy_Yakovlev1@epam.com
