### ISSUE TITLE
[Feature] Add annotations for all Complex elements

### ISSUE THREAD

**Issue by Supreme85** [epam/JDI#93]
Add special annotations for all [complex elements](https://github.com/epam/JDI/tree/master/Java/JDI/jdi-uitest-web/src/main/java/com/epam/jdi/uitests/web/selenium/elements/complex) like it done for Table(JTable), Dropdown (JDropdown), Menu (JMenu)
1. Create annotations with all necessary params
2. Update [WebCascadeInit](https://github.com/epam/JDI/blob/master/Java/JDI/jdi-uitest-web/src/main/java/com/epam/jdi/uitests/web/selenium/elements/WebCascadeInit.java) to use this annotations and fill elements

**Comment by dmorokov** [comment]
Add for elements:
- Checkbox
- CheckList
- RadioButtons
- MultiSelector

@RadioButtons(checked = By.cssSelector(".check"), unchecked = By.cssSelector(".uncheck"))
